### ISSUE TITLE
Test suite execution returns error 'Got the resultId undefined' on Azure DevOps

### ISSUE THREAD

**Issue by shararehl** [ghost-inspector/ghost-inspector-vsts-extension#20]
Hi,
I am running into a problem when executing my test suite in Azure DevOps, it returns 'Got the resultId undefined' error which leads to failure of execution of Polling for suite results. Therefore the build task fails with an error. I tried executing the test using both Postman and Powershell which was successful in both scenarios. Any idea what could be the reason for the error?

**Comment by aaronfay** [comment]
Hi @shararehl, can you verify what version of the `ghost-inspector-azure-devops` plugin you are using?

**Comment by shararehl** [comment]
Hi @aaronfay, we are using version 1.0.12.

**Comment by aaronfay** [comment]
Hey @shararehl, we've just published `1.0.13` that should log the error from that execution request, can you run your pipeline again and see if you get an error now?

**Comment by shararehl** [comment]
Hi @aaronfay 
I ran the test again but I am getting the same error. Task failed with the same error message. The Following is a screenshot of the error.
![Screenshot 2020-10-28 112848](https://user-images.githubusercontent.com/8971629/97376236-f9707500-1910-11eb-8861-52bc6f8e6a4b.png)

**Comment by aaronfay** [comment]
Hi @shararehl, can you jump over to [our website](https://ghostinspector.com/support/) and open a support chat using the chat widget in the bottom right of the screen, I'll pick up this issue from there.

Thanks

**Comment by aaronfay** [comment]
Hey @shararehl, I wanted to follow up on this as I didn't see anything come in support last week. Did you manage to sort the issue out? I suspect either the API key or the suite ID are incorrect, but without a little more info it will be hard to dig deeper into this. 

Let me know!

**Comment by shararehl** [comment]
Hey @aaronfay I am afraid the issue is not resolved. Both API key and the suite ID are correct. I sent a message in chat support. Thanks

**Comment by aaronfay** [comment]
This has been traced back to a changed API response from executing the suite with a data source assigned. We will put up a pull request shortly to address this.

**Comment by aaronfay** [comment]
This has been resolved in #22. @shararehl thanks for reporting 🙌
